site_name: EE4218 Labs
site_url: https://nus-ee4218.github.io/labs
theme:
  name: material
  features:
    - content.tooltips
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - abbr
  - attr_list
  - pymdownx.snippets
